### ISSUE TITLE
Bitcore 2.0.24 Invalid state: undefined 

### ISSUE THREAD

**Issue by matyushkins** [HorizenOfficial/insight-ui-zen#16]
HI.
nodejs 8.17

package.json:
```
{
    "description": "A full Horizen node build with Dashcore",
    "repository": "https://github.com/user/project",
    "license": "MIT",
    "readme": "README.md",
    "dependencies": {
      "bitcore-lib-zen": "github:ZencashOfficial/bitcore-lib-zen",
      "bitcore-node-zen": "github:ZencashOfficial/bitcore-node-zen",
      "insight-api-zen": "github:ZencashOfficial/insight-api-zen",
      "insight-ui-zen": "github:ZencashOfficial/insight-ui-zen"
    }
}
```

bitcore-node.json:
```
{
  "network": "livenet",
  "port": 3002,
  "services": [
    "bitcoind",
    "insight-api-zen",
    "insight-ui-zen",
    "web"
  ],
  "servicesConfig": {
    "bitcoind": {
      "spawn": {
        "datadir": "./data",
        "exec": "zend"
      }
    },
    "insight-ui-zen": {
      "routePrefix": "",
      "apiPrefix": "api"
    },
    "insight-api-zen": {
      "routePrefix": "api",
      "disableRateLimiter": true
    }
  }
}
```

ERROR:
```
[2021-10-12T12:33:48.072Z] error: Invalid state: undefined
Error
    at new NodeError (/opt/insight/node_modules/bitcore-node-zen/node_modules/bitcore-lib-zen/lib/errors/index.js:20:41)
    at Object.checkState (/opt/insight/node_modules/bitcore-node-zen/node_modules/bitcore-lib-zen/lib/util/preconditions.js:9:13)
    at Bitcoin._getAddressDetailsForTransaction (/opt/insight/node_modules/bitcore-node-zen/lib/services/bitcoind.js:1373:5)
    at /opt/insight/node_modules/bitcore-node-zen/lib/services/bitcoind.js:1393:33
    at /opt/insight/node_modules/async/lib/async.js:676:51
    at /opt/insight/node_modules/async/lib/async.js:726:13
    at /opt/insight/node_modules/async/lib/async.js:52:16
    at /opt/insight/node_modules/async/lib/async.js:264:21
    at /opt/insight/node_modules/async/lib/async.js:44:16
    at /opt/insight/node_modules/async/lib/async.js:723:17
[2021-10-12T12:33:48.072Z] info: Beginning shutdown
[2021-10-12T12:33:48.072Z] info: Stopping insight-ui-zen
[2021-10-12T12:33:48.072Z] error: uncaught exception: { Invalid state: undefined
Error
    at new NodeError (/opt/insight/node_modules/bitcore-node-zen/node_modules/bitcore-lib-zen/lib/errors/index.js:20:41)
    at Object.checkState (/opt/insight/node_modules/bitcore-node-zen/node_modules/bitcore-lib-zen/lib/util/preconditions.js:9:13)
    at Bitcoin._getAddressDetailsForTransaction (/opt/insight/node_modules/bitcore-node-zen/lib/services/bitcoind.js:1373:5)
    at /opt/insight/node_modules/bitcore-node-zen/lib/services/bitcoind.js:1393:33
    at /opt/insight/node_modules/async/lib/async.js:676:51
    at /opt/insight/node_modules/async/lib/async.js:726:13
    at /opt/insight/node_modules/async/lib/async.js:52:16
    at /opt/insight/node_modules/async/lib/async.js:264:21
    at /opt/insight/node_modules/async/lib/async.js:44:16
    at /opt/insight/node_modules/async/lib/async.js:723:17
  message: 'Invalid state: undefined',
  stack: 'Invalid state: undefined\nError\n    at new NodeError (/opt/insight/node_modules/bitcore-node-zen/node_modules/bitcore-lib-zen/lib/errors/index.js:20:41)\n    at Object.checkState (/opt/insight/node_modules/bitcore-node-zen/node_modules/bitcore-lib-zen/lib/util/preconditions.js:9:13)\n    at Bitcoin._getAddressDetailsForTransaction (/opt/insight/node_modules/bitcore-node-zen/lib/services/bitcoind.js:1373:5)\n    at /opt/insight/node_modules/bitcore-node-zen/lib/services/bitcoind.js:1393:33\n    at /opt/insight/node_modules/async/lib/async.js:676:51\n    at /opt/insight/node_modules/async/lib/async.js:726:13\n    at /opt/insight/node_modules/async/lib/async.js:52:16\n    at /opt/insight/node_modules/async/lib/async.js:264:21\n    at /opt/insight/node_modules/async/lib/async.js:44:16\n    at /opt/insight/node_modules/async/lib/async.js:723:17' }
[2021-10-12T12:33:48.072Z] error: Invalid state: undefined
Error
    at new NodeError (/opt/insight/node_modules/bitcore-node-zen/node_modules/bitcore-lib-zen/lib/errors/index.js:20:41)
    at Object.checkState (/opt/insight/node_modules/bitcore-node-zen/node_modules/bitcore-lib-zen/lib/util/preconditions.js:9:13)
    at Bitcoin._getAddressDetailsForTransaction (/opt/insight/node_modules/bitcore-node-zen/lib/services/bitcoind.js:1373:5)
    at /opt/insight/node_modules/bitcore-node-zen/lib/services/bitcoind.js:1393:33
    at /opt/insight/node_modules/async/lib/async.js:676:51
    at /opt/insight/node_modules/async/lib/async.js:726:13
    at /opt/insight/node_modules/async/lib/async.js:52:16
    at /opt/insight/node_modules/async/lib/async.js:264:21
    at /opt/insight/node_modules/async/lib/async.js:44:16
    at /opt/insight/node_modules/async/lib/async.js:723:17
[2021-10-12T12:33:48.072Z] info: Beginning shutdown
[2021-10-12T12:33:48.072Z] info: Stopping insight-ui-zen
```
And example  `Invalid Address: zszpcLB6C5B8QvfDbF2dYWXsrpac5DL9WRk`

**Comment by otoumas** [comment]
Hey @matyushkins Thanks for reaching us!
We are in the process of upgrading zend. We are right now testing the new version in Testnet and will go live in a month or so. 
There are a couple of changes that you should be aware of:
- From now on deployments will be done using tags, instead of master branch. Thanks to your issue we have seen that the documentation has not been updated 👍  🎉   we will do it asap.
- If you want to keep using zend 2.0.24 the tags you would need to use are: 
```
npm install -g bitcore-node#v3.1.3
bitcore-node create mynode
cd mynode
bitcore-node install insight-api#v0.4.4
bitcore-node install insight-ui
bitcore-node start
```
